baseURL = "https://lustrous-taffy-f0c5f1.netlify.app/categories/"
languageCode = "en-us"
title = "Hugo Blog"

[taxonomies]
  tag = "tags"
  categories = "categories"
  year = "year"
  month = "month"

[permalinks]
  blog = "/:filename/"
  post = "/:year/:month/:slug/"
  year = "/:year/"
  month = "/:year/:month/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Categories"
    pre = "book"
    url = "/categories/"
    weight = 4
  [[menu.main]]
    name = "Archive"
    pre = "eye"
    url = "/archives/"
    weight = 5

[params]
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "You just made a Hugo blog from scratch."
